#!/bin/sh 
#This job should be redirected to idqueue queue
#PBS -N 0.93TBLG
#PBS -l select=10:ncpus=24
#PBS -l walltime=12:00:00
#PBS -l place=scatter
#PBS -l accelerator_type="None"
#PBS -S /bin/sh@sdb -V

. /opt/modules/default/init/sh

#module swap PrgEnv-cray PrgEnv-intel
#module load intel 
#module load cray-hdf5

module swap PrgEnv-cray PrgEnv-intel/6.0.9
module load intel
module load cray-hdf5-parallel/1.12.0.0


cd $PBS_O_WORKDIR

#aprun -j 1 -n 480 -N 24 ./PhonFreq inp.dat_3X1 > mos2_3X1
aprun -j 1 -n 240 -N 24 ./PhonFreq_cray inp.dat.tblg_0.93 > graphene_0.93
#aprun -j 1 -n 1032 -N 24 ./out.o > correct_3X1

