#!/bin/sh 
#This job should be redirected to idqueue queue
#PBS -N 1.61BLG
#PBS -l select=1:ncpus=24
#PBS -l walltime=02:15:00
#PBS -l place=scatter
#PBS -l accelerator_type="None"
#PBS -S /bin/sh@sdb -V

. /opt/modules/default/init/sh

module swap PrgEnv-cray PrgEnv-intel
module load intel 
module load cray-hdf5
cd $PBS_O_WORKDIR

#aprun -j 1 -n 480 -N 24 ./PhonFreq inp.dat_3X1 > mos2_3X1
aprun -j 1 -n 24 -N 24 ./PhonFreq inp.dat_graphene > graphene_1.61
#aprun -j 1 -n 1032 -N 24 ./out.o > correct_3X1

